name: lazu_tree
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.1 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  husky: ^0.1.7
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  talker_flutter: ^4.7.6
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  firebase_core: ^3.13.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family: GeosansLight
      fonts:
        - asset: assets/fonts/geo_sans_light/GeosansLight.ttf
        - asset: assets/fonts/geo_sans_light/GeosansLight-Oblique.ttf
    - family: Kalufonia
      fonts:
        - asset: assets/fonts/kalufonia/Kalufonia-Regular.otf
    - family: Gloria_Hallelujah
      fonts:
        - asset: assets/fonts/Gloria_Hallelujah/GloriaHallelujah-Regular.ttf
